version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /docker/python
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /docker/node
    schedule:
      interval: weekly
